version: 2.1
general:
  branches:
    only:
     - master
orbs:
  python: circleci/python@1.2

workflows:
  main:
    jobs:
      - build-and-test

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8

    steps:
      - checkout
      - run:
          name: build main
          command: make
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements.txt
      - python/install-packages:
          pkg-manager: pip
          args: pytest
      - run:
          name: Run tests
          command: pytest
